global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'api-propostas'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-propostas:8080']